name: bluetooth_imo_sensor
description: A new Flutter project to connect to a Bluetooth IMO sensor and display its data.


version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
